#  Mukul's Personal Website is a Personal Website 
#  Copyright (C) 2024 Mukul Kedia

#  Mukul's Personal Website is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published
#  by the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  Mukul's Personal Website is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with Mukul's Personal Website. If not, see <https://www.gnu.org/licenses/>.

name: personal-website
type: module
version: 1.0.0
license: AGPL-3.0-only
scripts:
  dev: astro dev
  build: astro build
  preview: astro preview
  astro: astro
  format: prettier . --write
  hook: lefthook install
devDependencies:
  '@astrojs/tailwind': ^5.1.0
  '@playform/compress': ^0.0.13
  astro: ^4.12.2
  daisyui: ^4.12.10
  prettier-plugin-astro: ^0.14.1
  tailwindcss: ^3.4.6
  typescript: ^5.5.4
packageManager: >-
  pnpm@9.6.0+sha512.38dc6fba8dba35b39340b9700112c2fe1e12f10b17134715a4aa98ccf7bb035e76fd981cf0bb384dfa98f8d6af5481c2bef2f4266a24bfa20c34eb7147ce0b5e
